### ISSUE TITLE
dated default ruleset

### ISSUE THREAD

**Issue by jawz101** [arantius/karma-blocker#15]
Take a look at this page
http://www.androidpolice.com/2015/08/31/35-new-and-notable-android-games-from-the-last-2-weeks-81815-83115/

I don't give much credence to CDN's for instance fonts.gstatic.com is part of Google's Beautify the Web concept yet is a tracker. https://developers.google.com/fonts/terms

I also wouldn't weight https connections so forgivingly because ads have been sent over https for a while now.  Google, for instance, pushes ads and trackers over https for a while.  They sideload it with browser options to compress images by sending it through Google's proxy servers to save bandwidth... then spit things back out compressed and encrypted to ensure you see the ads too.  On Android, for instance, if you turn the bandwidth saving feature on in Chrome all traffic gets this treatment and suddenly ABP for Android and Adaway are circumvented.

**Comment by jawz101** [comment]
Sorry for the blast of enhancement requests... I was just brainstorming for a while.

**Comment by arantius** [comment]
Ideas are always welcome, as long as you accept that this is a small side project, so they can't necessarily be acted upon.

The middling/poor quality of the default rules is almost a feature, not a bug.  They're intended mostly as a concrete example of what the rules can do.  They're broken enough that you'll need to learn how to maintain them yourself.

Allowing CDNs is just a personal preference; I trend towards blocking third-party content, but this breaks too many things.
