### ISSUE TITLE
extend monitoring to graph & trend how different domains use certain techniques

### ISSUE THREAD

**Issue by jawz101** [arantius/karma-blocker#17]
If this add-on had the ability to show hit counters on methods different domains use to embed ads that would be interesting.

I'm envisioning something like a graphic equalizer where you could adjust weights for, say, transparent pixels or 3rd party with sliders and an overall and current webpage hits behind it to see if the weights affect the page.

**Comment by arantius** [comment]
This sounds like a nice idea, but realistically it's not going to happen given how much effort it represents.
